import 'package:hotel_villa_france/utils/models/room.dart';

List<Room> roomsList = [
  Room(
      name: 'suproom',
      profileImage: 'assets/images/sup_chambe.png',
      imagePath: List<String>.generate(
          7, (index) => "assets/images/chamb_sup/chamb_sup_$index.jpg"),
      aminities: [
        "Air conditioning",
        "Bidet",
        "Desk",
        "En-suite bathroom",
        "Entire unit located\non ground floor",
        "Entire unit wheelchair\naccessible",
        "International outlet",
        "Linen",
        "Minibar",
        "Upper floors accessible\nby stairs only",
        "Wardrobe or closet",
        "Flat-screen TV",
        "Free toiletries",
        "Hairdryer",
        "Hardwood or Parquet floors",
        "Heating",
        "Interconnected room(s)\navailable",
        "Patio",
        "Safety deposit box",
        "Shower",
        "Single-room air conditioning\nfor guest accommodation",
        "Upper floors accessible by\nelevator",
        "Slippers",
        "Socket near the bed",
        "Soundproofing",
        "Telephone",
        "Toilet",
        "Toilet paper",
        "Towels",
        "TV",
        "Wake-up service",
      ],
      services: [
        "Free-to-use smartphone (Free)",
        "Safe-deposit box (Free)",
        "Luggage storage (Free)",
        "Childcare (60 MAD / Once / Per Accommodation)",
        "Massage (15 MAD / Once / Per Guest)"
      ],
      infos: [55, 2, 1],
      price: "-15% ",
      bookinLink: "https://leroyal.com/en/AFRICA/grand-hotel-villa",
      details:
          "Welcome to our superior rooms which boast 25sqm of space and a large bed, offering an incomparable view to the Bay of Tangier or on the property's gardens and pool. The bed's wooden-sculpted headboard and locally painted wall mural add to the elegant décor. An office corner and a small seating can also be found in each Superior Room."),
  Room(
      name: 'duplexroom',
      profileImage: 'assets/images/duplex_room.png',
      imagePath: List<String>.generate(
          3, (index) => "assets/images/duplex/duplex_$index.jpg"),
      aminities: [
        "Balcony",
        "Bathtub",
        "Air conditioning",
        "Attached bathroom",
        "Flat-screen TV",
        "Soundproof",
        "Terrace",
        "Minibar",
        "Free WiFi",
        "Free toiletries",
        "Bathrobe",
        "Bidet",
        "Toilet",
        "Towels",
        "Slippers",
        "Hairdryer",
        "Toilet paper",
        "Upper floors accessible\nby elevator",
        "Linens",
        "Wardrobe or closet",
        "Minibar",
        "Air conditioning",
        "Desk",
        "Electric blankets",
        "Fan",
        "Heating",
        "Hypoallergenic",
        "No smoking",
        "Safety deposit box",
        "Satellite channels",
        "Sitting area",
        "Socket near the bed",
        "Soundproof",
        "Telephone",
        "Wake-up service",
        "Wake-up service/Alarm clock",
        "Work desk"
      ],
      services: [
        "Free-to-use smartphone (Free)",
        "Safe-deposit box (Free)",
        "Luggage storage (Free)",
        "Childcare (60 MAD / Once / Per Accommodation)",
        "Massage (15 MAD / Once / Per Guest)"
      ],
      infos: [55, 3, 1],
      price: "-15% ",
      bookinLink: "https://leroyal.com/en/AFRICA/grand-hotel-villa",
      details:
          "For the ultimate comfort; reserve a luxury suite on two floors. The upper level has a bedroom with a large bed and balcony that overlooks the gardens and pool. The lower level features a Moroccan-style living area and television viewing area, in addition to a terrace that offers direct access to the garden and pool."),
  Room(
      name: 'suitesenior',
      profileImage: 'assets/images/suite_senior.png',
      imagePath: List<String>.generate(
          2, (index) => "assets/images/senior/senior_$index.jpg"),
      price: "-15% ",
      bookinLink: "https://leroyal.com/en/AFRICA/grand-hotel-villa",
      aminities: [
        "Bath",
        "Air conditioning",
        "Ensuite bathroom",
        "Flat-screen TV",
        "Soundproofing",
        "Minibar",
        "Free toiletries",
        "Bathrobe",
        "Safety deposit box",
        "Bidet Toilet",
        "Hardwood or parquet floors",
        "Towels",
        "Linen",
        "Socket near the bed",
        "Desk Seating Area",
        "TV",
        "Slippers",
        "Telephone",
        "Interconnected room(s)\navailable",
        "Heating",
        "Hairdryer",
        "Fan",
        "Entire unit wheelchair\naccessible",
        "Executive lounge access\nWardrobe or closet",
        "Extra long beds (> 2 metres)",
        "Single-room air conditioning\nfor guest accommodation",
        "Toilet paper",
        "Upper floors accessible\nby elevator Linens",
        "Upper floors accessible\nby stairs only",
        "Wake up service/Alarm clock",
        "Wake-up service",
      ],
      services: [
        // "Free-to-use smartphone (Free)",
        // "Safe-deposit box (Free)",
        // "Luggage storage (Free)",
        // "Childcare (60 MAD / Once / Per Accommodation)",
        // "Massage (15 MAD / Once / Per Guest)"
      ],
      infos: [70, 3, 2],
      details: "Comfortable, spacious quarters await visitors who reserve a senior suite, as well as a splendid view out to sea. This suite has a separate bedroom with a large bed and an admirable wood-sculpted headboard. There is also a separate living room with its own television, as well as an office corner."),
  Room(
      name: 'matisse',
      profileImage: 'assets/images/matisse.png',
      imagePath: List<String>.generate(
          2, (index) => "assets/images/matisse/matisse_$index.jpg"),
      aminities: [
      ],
      services: [
      ],
      infos: [0, 1, 0],
      price: "-15% ",
      details:
          "Henri Matisse (31 December 1869 - 3 November 1954), one of the undisputed masters of 20th century art, was a French artist, known for his use of colour and his fluid and original draughtsmanship. He was a draughtsman, printmaker, and sculptor, but is known primarily as a painter. Matisse is commonly regarded, along with Picasso and Marcel Duchamp, as one of the three artists who helped to define the revolutionary developments in the plastic arts in the opening decades of the 20th century, responsible for significant developments in painting and sculpture. Although he was initially labeled a Fauve (wild beast), by the 1920s he was increasingly hailed as an upholder of the classical tradition in French painting. His mastery of the expressive language of colour and drawing, displayed in a body of work spanning over a half-century, won him recognition as a leading figure in modern art.\nEarly life and education\nHenri Matisse was born in Le Cateau-Cambresis, Nord, France. He grew up in Bohain-en-Vermandois, Picardy, France, where his parents owned a flower business; he was their first son. In 1887 he went to Paris to study law, working as a court administrator in Le Cateau-Cambrésis after gaining his qualification. He first started to paint in 1889, after his mother brought him art supplies during a period of convalescence following an attack of appendicitis. He discovered \"a kind of paradise\" as he later described it, and decided to become an artist, deeply disappointing his father. In 1891, he returned to Paris to study art at the Académie Julian and became a student of William-Adolphe Bouguereau and Gustave Moreau. Initially he painted still-lifes and landscapes in a traditional style, at which he achieved reasonable proficiency. Matisse was influenced by the works of earlier masters such as Jean-Baptiste-Siméon Chardin, Nicolas Poussin, and Antoine Watteau, as well as by modern artists such as Edouard Manet, and by Japanese art. Chardin was one of Matisse's most admired painters; as an art student he made copies of four Chardin paintings in the Louvre."),
];
